from datetime import timedelta

SECRET_KEY = "dTHRLCTgD4Y189UROiIQ1ts0KSm3GsAdц"
SQLALCHEMY_DATABASE_URI = "postgresql://admin:admin@34.125.14.119:15433/hackaton"
SQLALCHEMY_TRACK_MODIFICATIONS = False

JWT_AUTH_URL_RULE = "/login"
JWT_AUTH_USERNAME_KEY = "username"
JWT_AUTH_PASSWORD_KEY = "password"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_DELTA = timedelta(seconds=300)


def get_parameters():
    data = {
        "SECRET_KEY": SECRET_KEY,
        "SQLALCHEMY_DATABASE_URI": SQLALCHEMY_DATABASE_URI,
        "SQLALCHEMY_TRACK_MODIFICATIONS": SQLALCHEMY_TRACK_MODIFICATIONS,
        "JWT_AUTH_URL_RULE": JWT_AUTH_URL_RULE,
        "JWT_AUTH_USERNAME_KEY": JWT_AUTH_USERNAME_KEY,
        "JWT_AUTH_PASSWORD_KEY": JWT_AUTH_PASSWORD_KEY,
        "JWT_ALGORITHM": JWT_ALGORITHM,
        "JWT_EXPIRATION_DELTA": JWT_EXPIRATION_DELTA
    }
    return data
